### ISSUE TITLE
Fix print command

### ISSUE THREAD

**Issue by hbueno** [brunopdias/semanainvernogeofisica#1]
Oi Bruno,

sugiro uma pequena correção nessa linha:

https://github.com/brunopdias/semanainvernogeofisica/blob/master/modelagem/m8r/ac_homog/SConstruct#L197

Ao rodar o SConstruct:

```
scons: Reading SConscript files ...
model parameters:  {'vp': 2000.0, 'rho': 1000.0}
NameError: name 'prin' is not defined:
```

**Comment by brunopdias** [comment]
Valeu Henrique!
